export const ROUTE = {
  landing: '',
  login: 'login',
  logout: 'logout',
  admin: 'admin',
  latestNews: 'latest-news',
  editNews: 'edit-news',
  allMovies: 'all-movies',
  createMovie: 'create-movie',
  web3project: 'web3-project',
  createProject: 'create-project',
  calendar: 'calendar',
  createCalendar: 'create-calendar',
  casting: 'casting',
  createCasting: 'create-casting',
  settings: 'settings',
  notfound: '*',
};
