export const ROUTE = {
  landing: '',
  login: 'login',
  admin: 'admin',
  mainSlider: 'main-slide',
  createSlide: 'create-slide',
  allMovies: 'all-movies',
  createMovie: 'create-movie',
  web3project: 'web3-project',
  createProject: 'create-project',
  calendar: 'calendar',
  createCalendar: 'create-calendar',
  casting: 'casting',
  createCasting: 'create-casting',
  emailVerify: 'email-verify',
  forgotPassword: 'forgot-password',
  notfound: '*',
};
